config/routes.rb
Derm::Application.routes.draw do

  resources :patients do
    resources :dhermatologic_visits
    resource :patient_profile
  end

  root :to => "articles#index"
  resources :articles
  resources :users
  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :date_of_birth, :first_name, :last_name, :mobile_number
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :date_of_birth, :presence => true
  validates :mobile_number, :presence => true
  
  has_one :patient_profile, :dependent => :destroy 
  belongs_to :user
  has_many :dhermatologic_visits, :order => "visit_date DESC", :dependent => :destroy
  
  def long_name
    first_name + ' '+last_name
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
       @patient.create_patient_profile
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth, :start_year => Time.now.year - 100, :end_year => Time.now.year %>
  </div>
  <div class="field">
    <%= f.label :mobile_number %><br />
    <%= f.text_field :mobile_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<%= div_for patient do %>
  <h3>
  	<%= 'Patient Name: '%>
    <%= link_to patient.long_name, patient %>
    <span class='actions'>
      <%= link_to "Edit", edit_patient_path(patient) %>
      <%= link_to "Delete", patient, :confirm => "Are you sure?",
:method => :delete %>
    </span>
  </h3>
  <p>
    <b><%= 'File Number: ' %> </b>  
      <%= @patient.id %> 
 </p>
  <p>  
    <b><%= 'Date of birth: ' %> </b>  
      <%= @patient.date_of_birth %> </p>
    <p>
    <b><%= 'Mobile number: ' %></b>
    <%= @patient.mobile_number %>
 </p><p></p>

<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Date of birth</th>
    <th>Mobile number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patients.each do |patient| %>
  <tr>
    <td><%= patient.first_name %></td>
    <td><%= patient.last_name %></td>
    <td><%= patient.date_of_birth %></td>
    <td><%= patient.mobile_number %></td>
    <td><%= link_to 'Show', patient %></td>
    <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
    <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<%= render @patient %>
<h2> Patient Profile </h2> </p>
<div id='edit_patient_profile_title'>
</div>	
<%= link_to "Open Patient Profile form", edit_patient_patient_profile_path(@patient, :format => :js),
         :remote => true,  :id => 'edit_patient_profile_link' %>

<h3>Previous Dhermatologic Visits:</h3>
<div id="dhermatologic_visits">
	<%= render @patient.dhermatologic_visits %>
	</p>
</div>
</p>
<script> 
$(document).ready(function(){
  $("#new_dhermatologic_visit_title").click(function(){
    $("#new_dhermatologic_visit").slideToggle("slow");
  });
});
</script>
<div id='new_dhermatologic_visit_title'>
	<h2> New Dhermatologic Visit </h2> </p>
</div>	
<%= link_to "Open Dhermatologic Visit form", new_patient_dhermatologic_visit_path(@patient, :format => :js),
         :remote => true,  :id => 'new_dhermatologic_visit_link' %>