config/routes.rb
Derm::Application.routes.draw do

  resources :patients do
    resources :dhermatologic_visits
    resource :patient_profile
  end

  root :to => "articles#index"
  resources :articles
  resources :users
  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

end

app/models/dhermatologic_visit.rb
class DhermatologicVisit < ActiveRecord::Base
  attr_accessible :chief_complaint, :diagnosis, :ex_general, :history_illness, :medication, :patient_id, :procedures, :visit_date, :weight
  validates :chief_complaint, :presence => true
  
  belongs_to :patient
end

app/controllers/dhermatologic_visits_controller.rb
class DhermatologicVisitsController < ApplicationController
  before_filter :load_patient
  # GET /dhermatologic_visits
  # GET /dhermatologic_visits.json
  def index
    @dhermatologic_visits = @patient.dhermatologic_visits.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dhermatologic_visits }
    end
  end

  # GET /dhermatologic_visits/1
  # GET /dhermatologic_visits/1.json
  def show
    @dhermatologic_visit = @patient.dhermatologic_visits.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dhermatologic_visit }
    end
  end

  # GET /dhermatologic_visits/new
  # GET /dhermatologic_visits/new.json
  def new
    @dhermatologic_visit = @patient.dhermatologic_visits.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @dhermatologic_visit }
    end
  end

  # GET /dhermatologic_visits/1/edit
  def edit
    @dhermatologic_visit = @patient.dhermatologic_visits.find(params[:id])
  end

  # POST /dhermatologic_visits
  # POST /dhermatologic_visits.json
  def create
    @dhermatologic_visit = @patient.dhermatologic_visits.new(params[:dhermatologic_visit])

    respond_to do |format|
      if @dhermatologic_visit.save
        format.html { redirect_to @patient, notice: 'Dhermatologic visit was successfully created.' }
        format.json { render json: @dhermatologic_visit, status: :created, location: @dhermatologic_visit }
      else
        format.html { render action: "new" }
        format.json { render json: @dhermatologic_visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dhermatologic_visits/1
  # PUT /dhermatologic_visits/1.json
  def update
    @dhermatologic_visit = @patient.dhermatologic_visits.find(params[:id])

    respond_to do |format|
      if @dhermatologic_visit.update_attributes(params[:dhermatologic_visit])
        format.html { redirect_to @patient, notice: 'Dhermatologic visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dhermatologic_visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dhermatologic_visits/1
  # DELETE /dhermatologic_visits/1.json
  def destroy
    @dhermatologic_visit = @patient.dhermatologic_visits.find(params[:id])
    @dhermatologic_visit.destroy

    respond_to do |format|
      format.html { redirect_to @patient, :notice => "dhermatologic visit deleted" }
      format.json { head :no_content }
    end
  end
  private
    def load_patient
      @patient = Patient.find(params[:patient_id])
    end  
end

app/helpers/dhermatologic_visits_helper.rb
module DhermatologicVisitsHelper
end

app/views/dhermatologic_visits/_dhermatologic_visit.html.erb
<%= div_for dhermatologic_visit do %>
  <h3>
    <%= 'Date: '+ dhermatologic_visit.visit_date.to_s() %> 
    <span class='actions'>
      <%= link_to 'Delete', [@patient, dhermatologic_visit], :confirm => 'Are you sure?', :method => :delete %>
    </span>
  </h3>
  <%= 'Chief Complaint: '+ dhermatologic_visit.chief_complaint %>
<% end %>

app/views/dhermatologic_visits/_form.html.erb
<%= form_for(@dhermatologic_visit) do |f| %>
  <% if @dhermatologic_visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dhermatologic_visit.errors.count, "error") %> prohibited this dhermatologic_visit from being saved:</h2>

      <ul>
      <% @dhermatologic_visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :visit_date %><br />
    <%= f.date_select :visit_date %>
  </div>
  <div class="field">
    <%= f.label :chief_complaint %><br />
    <%= f.text_area :chief_complaint %>
  </div>
  <div class="field">
    <%= f.label :history_illness %><br />
    <%= f.text_area :history_illness %>
  </div>
  <div class="field">
    <%= f.label :ex_general %><br />
    <%= f.text_field :ex_general %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :diagnosis %><br />
    <%= f.text_area :diagnosis %>
  </div>
  <div class="field">
    <%= f.label :medication %><br />
    <%= f.text_area :medication %>
  </div>
  <div class="field">
    <%= f.label :procedures %><br />
    <%= f.text_area :procedures %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dhermatologic_visits/edit.html.erb
<h1>Editing dhermatologic_visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @dhermatologic_visit %> |
<%= link_to 'Back', dhermatologic_visits_path %>

app/views/dhermatologic_visits/index.html.erb
<h1>Listing dhermatologic_visits</h1>

<table>
  <tr>
    <th>Patient</th>
    <th>Visit date</th>
    <th>Chief complaint</th>
    <th>History illness</th>
    <th>Ex general</th>
    <th>Weight</th>
    <th>Diagnosis</th>
    <th>Medication</th>
    <th>Procedures</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dhermatologic_visits.each do |dhermatologic_visit| %>
  <tr>
    <td><%= dhermatologic_visit.patient_id %></td>
    <td><%= dhermatologic_visit.visit_date %></td>
    <td><%= dhermatologic_visit.chief_complaint %></td>
    <td><%= dhermatologic_visit.history_illness %></td>
    <td><%= dhermatologic_visit.ex_general %></td>
    <td><%= dhermatologic_visit.weight %></td>
    <td><%= dhermatologic_visit.diagnosis %></td>
    <td><%= dhermatologic_visit.medication %></td>
    <td><%= dhermatologic_visit.procedures %></td>
    <td><%= link_to 'Show', dhermatologic_visit %></td>
    <td><%= link_to 'Edit', edit_dhermatologic_visit_path(dhermatologic_visit) %></td>
    <td><%= link_to 'Destroy', dhermatologic_visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dhermatologic visit', new_dhermatologic_visit_path %>

app/views/dhermatologic_visits/new.html.erb
<%= form_for([@patient, @patient.dhermatologic_visits.new],
          :html => {:style => 'display: none;'}) do |f| %>
          

  <div class="field">
    <%= f.label :visit_date %><br />
    <%= f.date_select :visit_date %>
  </div>
  <div class="field">
    <%= f.label :chief_complaint %><br />
    <%= f.text_area :chief_complaint %>
  </div>
  <div class="field">
    <%= f.label :history_illness %><br />
    <%= f.text_area :history_illness %>
  </div>
  <div class="field">
    <%= f.label :ex_general %><br />
    <%= f.text_field :ex_general %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :diagnosis %><br />
    <%= f.text_area :diagnosis %>
  </div>
  <div class="field">
    <%= f.label :medication %><br />
    <%= f.text_area :medication %>
  </div>
  <div class="field">
    <%= f.label :procedures %><br />
    <%= f.text_area :procedures %>
  </div>
  <div class="actions">
    <%= f.submit 'Add' %><br />
  </div>

<% end %>

app/views/dhermatologic_visits/new.js.erb
$("<%= escape_javascript render(:file => 'dhermatologic_visits/new.html.erb') %>").insertAfter('#new_dhermatologic_visit_title');
$('#new_dhermatologic_visit').slideDown();
$('#new_dhermatologic_visit_link').hide();

app/views/dhermatologic_visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Visit date:</b>
  <%= @dhermatologic_visit.visit_date %>
</p>

<p>
  <b>Chief complaint:</b>
  <%= @dhermatologic_visit.chief_complaint %>
</p>

<p>
  <b>History illness:</b>
  <%= @dhermatologic_visit.history_illness %>
</p>

<p>
  <b>Ex general:</b>
  <%= @dhermatologic_visit.ex_general %>
</p>

<p>
  <b>Weight:</b>
  <%= @dhermatologic_visit.weight %>
</p>

<p>
  <b>Diagnosis:</b>
  <%= @dhermatologic_visit.diagnosis %>
</p>

<p>
  <b>Medication:</b>
  <%= @dhermatologic_visit.medication %>
</p>

<p>
  <b>Procedures:</b>
  <%= @dhermatologic_visit.procedures %>
</p>


<%= link_to 'Edit', edit_dhermatologic_visit_path(@dhermatologic_visit) %> |
<%= link_to 'Back', dhermatologic_visits_path %>